spring:
   application:
      name: demoservice
      database: h2
      console: true
      path: /h2
   datasource:
      platform: h2
      url: jdbc:h2://localhost:8080/h2
      username: user
      password: user
      driverClassName: org.h2.Driver
server:
   port: 8080
   



---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 4431